//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.DeliveredBooks = new HashSet<DeliveredBook>();
            this.EntrustedBooks = new HashSet<EntrustedBook>();
            this.EntrustedInfoes = new HashSet<EntrustedInfo>();
        }
    
        public int BookId { get; set; }
        public string Name { get; set; }
        public string Publisher { get; set; }
        public string Writer { get; set; }
        public short PageNo { get; set; }
        public string Category { get; set; }
        public string SaloonShelf { get; set; }
        public byte[] Image { get; set; }
        public bool Status { get; set; }
    
        public virtual Book Books1 { get; set; }
        public virtual Book Book1 { get; set; }
        public virtual Confirm Confirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveredBook> DeliveredBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrustedBook> EntrustedBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrustedInfo> EntrustedInfoes { get; set; }
    }
}
