//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.Confirm = new HashSet<Confirm>();
            this.DeliveredBooks = new HashSet<DeliveredBooks>();
            this.EntrustedBooks = new HashSet<EntrustedBooks>();
            this.EntrustedInfo = new HashSet<EntrustedInfo>();
        }
    
        public int BookId { get; set; }
        public string Name { get; set; }
        public string Publisher { get; set; }
        public string Writer { get; set; }
        public short PageNo { get; set; }
        public string Category { get; set; }
        public string SaloonShelf { get; set; }
        public byte[] Image { get; set; }
        public bool Status { get; set; }
    
        public virtual Books Books1 { get; set; }
        public virtual Books Books2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirm> Confirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveredBooks> DeliveredBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrustedBooks> EntrustedBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntrustedInfo> EntrustedInfo { get; set; }
    }
}
